name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust:
          - '1.64.0'
          - '1.65.0'
          - 'nightly'
        php:
          - '7.0'
          - '7.4'
          - '8.0'
          - '8.2'
        os:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: installing PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: ${{ matrix.php }}

      - name: installing Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: cache
        uses: Swatinem/rust-cache@v2.0.0

      - name: check
        if: matrix.rust == '1.65.0'
        run: |
          cargo fmt --all -- --check
          cargo clippy

      - name: test
        run: cargo test --all --doc

      - name: build
        run: cargo build 

      - name: examples
        run: |
          cargo run --example debug
